version: '3.1'
services:
  mysql:
    image: mysql:5.7.29
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 3333:3306
    volumes:
      - 'vol_mysql:/var/lib/mysql'
volumes:
  vol_mysql:
    driver: local