version: '3.1'
services:
  mysql:
    image: mysql:5.7.29
    network_mode: host  
 #   command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    #  - MYSQL_ROOT_PASSWORD=Hamada1 
    ports:
     - 3333:3306
    volumes:
      - 'vol_mysql:/var/lib/mysql'
volumes:
  vol_mysql:
    driver: local